repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy

  - repo: local
    hooks:
      - id: eslint-ts
        name: eslint (ts/tsx)
        entry: npx eslint
        language: node
        types: [ts, tsx]
        args: [--fix]
        files: ^frontend/
