version: '3.8'

services:
  arkstream-zookeeper:
    container_name: arkstream-zookeeper
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  arkstream-kafka:
    container_name: arkstream-kafka
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=arkstream-zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - arkstream-zookeeper

  arkstream-mongo:
    container_name: arkstream-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  arkstream-postgres:
    container_name: arkstream-postgres
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: market_data
    volumes:
      - pg_data:/var/lib/postgresql/data
  arkstream-vault-dev:
    image: hashicorp/vault:1.19.5
    container_name: arkstream-vault-dev
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: vault server -dev

  arkstream-vault:
    container_name: arkstream-vault
    image: hashicorp/vault:1.19.5
    ports:
      - "18201:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ../vault/config:/vault/config
      - ../vault/policies:/vault/policies
    command: vault server -config=/vault/config/vault.hcl

volumes:
  mongo_data:
  pg_data:
