version: "3.9"

services:
  vault:
    image: vault:1.13.3
    container_name: ark_vault
    restart: unless-stopped
    command: server  # ← 本番運用では必ず server
    ports:
      - "443:8200"  # HTTPSポートを公開（443にマッピング）
    volumes:
      - ./Storage/vault/data:/vault/data
      - ./vault/config:/vault/config     # vault.hcl をここに置く
      - ./vault/cert:/vault/cert         # TLS証明書を置く
    cap_add:
      - IPC_LOCK                         # mlock用（disable_mlock=trueなら無効化される）
    networks:
      - arkstream_net
    depends_on:
      - consul                           # consulが先に起動するように
    environment:
      VAULT_ADDR: "https://localhost:8200"

  consul:
    image: consul:1.15.4
    container_name: ark_consul
    restart: unless-stopped
    ports:
      - "8500:8500"   # ConsulのUI/API
    networks:
      - arkstream_net

  mongo:
    image: mongo:6
    container_name: ark_mongo
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./Storage/mongo/data:/data/db
    networks:
      - arkstream_net

  kafka:
    image: bitnami/kafka:3.5
    container_name: ark_kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - ./Storage/kafka/data:/var/lib/kafka/data
    networks:
      - arkstream_net

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: ark_zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - arkstream_net

networks:
  arkstream_net:
    driver: bridge
