version: "3.9"

services:
  vault:
    image: vault:1.15.2
    container_name: ark_vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      VAULT_LOCAL_CONFIG: |
        {
          "listener": [{
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_disable": 1
            }
          }],
          "storage": {
            "file": {
              "path": "/vault/file"
            }
          },
          "api_addr": "http://0.0.0.0:8200",
          "ui": true
        }
    volumes:
      - ark_vault_data:/vault/file
    cap_add:
      - IPC_LOCK

  postgres:
    image: postgres:15
    container_name: ark_postgres
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"   # 外部からアクセス禁止
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: arkstream
      POSTGRES_DB: arkstream
    volumes:
      - ark_postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: ark_mongo
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017" # 外部からアクセス禁止
    volumes:
      - ark_mongo_data:/data/db

  kafka:
    image: bitnami/kafka:latest
    container_name: ark_kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.11.10:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: ark_zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

volumes:
  ark_vault_data:
  ark_postgres_data:
  ark_mongo_data:
