version: "3.9"

services:
  vault:
    image: vault:1.13.3
    container_name: profinaut_vault
    restart: unless-stopped
    command: server
    ports:
      - "443:8200"
    volumes:
      - ./Storage/vault/data:/vault/data
      - ./vault/config:/vault/config
      - ./vault/cert:/vault/cert
    cap_add:
      - IPC_LOCK
    networks:
      - profinaut_net
    depends_on:
      - consul
    environment:
      VAULT_ADDR: "https://localhost:8200"

  consul:
    image: consul:1.15.4
    container_name: profinaut_consul
    restart: unless-stopped
    ports:
      - "8500:8500"
    volumes:
      - consul_data:/consul/data    # ← これを追加
    networks:
      - profinaut_net

  mongo:
    image: mongo:6
    container_name: profinaut_mongo
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./Storage/mongo/data:/data/db
    networks:
      - profinaut_net

  kafka:
    image: bitnami/kafka:3.5
    container_name: profinaut_kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - ./Storage/kafka/data:/var/lib/kafka/data
    networks:
      - profinaut_net

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: profinaut_zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - profinaut_net

networks:
  profinaut_net:
    driver: bridge

volumes:
  consul_data:   # ← 永続化ボリュームを定義
