global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rust_app'
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: 'kafka'
    static_configs:
      - targets: ['host.docker.internal:9308']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['host.docker.internal:9216']

  - job_name: 'postgres'
    static_configs:
      - targets: ['host.docker.internal:9187']
