version: '3.8'

services:

  vault:
    image: hashicorp/vault:1.15.2
    container_name: ark_vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    volumes:
      - ./vault:/vault/config
    cap_add:
      - IPC_LOCK
    command: vault server -dev

  postgres:
    image: postgres:15
    container_name: ark_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: arkuser
      POSTGRES_PASSWORD: example
      POSTGRES_DB: arkstream
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6.0
    container_name: ark_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: ark_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: ark_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  prometheus:
    image: prom/prometheus:latest
    container_name: ark_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: ark_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

  loki:
    image: grafana/loki:2.9.2
    container_name: ark_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./docker/loki-config.yml:/etc/loki/config.yml

  promtail:
    image: grafana/promtail:2.9.2
    container_name: ark_promtail
    volumes:
      - /var/log:/var/log
      - ./docker/promtail-config.yml:/etc/promtail/config.yml

volumes:
  pgdata:
  mongodata:
  grafana-storage:
