name: Rust Test & Docker Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  rust-test:
    name: 🧪 Rust Tests with Vault
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 📥 Install Vault CLI
        run: |
          curl -fsSL https://releases.hashicorp.com/vault/1.15.2/vault_1.15.2_linux_amd64.zip -o vault.zip
          mkdir -p vault-bin
          unzip -o vault.zip -d vault-bin
          sudo mv vault-bin/vault /usr/local/bin/
          vault --version

      - name: 🚀 Start Vault Dev Server
        run: |
          nohup vault server -dev -dev-root-token-id="root-token" > vault.log 2>&1 &
          sleep 5
        env:
          VAULT_ADDR: http://127.0.0.1:8200

      - name: 🔐 Seed Secrets for Test
        env:
          VAULT_ADDR: http://127.0.0.1:8200
          VAULT_TOKEN: root-token
        run: |
          vault kv put secret/profinaut/testenv \
            POSTGRES_URL="postgres://testuser:testpass@localhost:5432/testdb" \
            POSTGRES_PASSWORD=devpass \
            MONGO_URI="mongodb://localhost:27017" \
            KAFKA_BROKER="localhost:9092" \
            BINANCE_API_KEY="dummy_key" \
            BINANCE_SECRET_KEY="dummy_secret"

      - name: 📤 Fetch Secrets for Rust Test
        env:
          VAULT_ADDR: http://127.0.0.1:8200
          VAULT_TOKEN: root-token
        run: |
          vault kv get -format=json secret/profinaut/testenv > secret.json
          POSTGRES_URL=$(jq -r ".data.data.POSTGRES_URL" secret.json)
          echo "POSTGRES_URL=$POSTGRES_URL" >> $GITHUB_ENV

      - name: 🧪 Run Rust Tests
        env:
          POSTGRES_URL: ${{ env.POSTGRES_URL }}
        run: cargo test -- --test-threads=1

  docker-build:
    name: 🐳 Docker Build with Vault Secrets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 📥 Install Vault CLI
        run: |
          curl -fsSL https://releases.hashicorp.com/vault/1.15.2/vault_1.15.2_linux_amd64.zip -o vault.zip
          mkdir -p vault-bin
          unzip -o vault.zip -d vault-bin
          sudo mv vault-bin/vault /usr/local/bin/
          vault --version

      - name: 🚀 Start Vault Dev Server
        run: |
          nohup vault server -dev -dev-root-token-id="root-token" > vault.log 2>&1 &
          sleep 5
        env:
          VAULT_ADDR: http://127.0.0.1:8200

      - name: 🔐 Seed Secrets for Docker Build
        env:
          VAULT_ADDR: http://127.0.0.1:8200
          VAULT_TOKEN: root-token
        run: |
          vault kv put secret/profinaut/testenv \
            POSTGRES_PASSWORD=devpass \
            MONGO_URI="mongodb://localhost:27017" \
            KAFKA_BROKER="localhost:9092"

      - name: 📤 Fetch Secrets for Docker Build
        env:
          VAULT_ADDR: http://127.0.0.1:8200
          VAULT_TOKEN: root-token
        run: |
          vault kv get -format=json secret/profinaut/testenv > secret.json
          POSTGRES_PASSWORD=$(jq -r ".data.data.POSTGRES_PASSWORD" secret.json)
          MONGO_URI=$(jq -r ".data.data.MONGO_URI" secret.json)
          KAFKA_BROKER=$(jq -r ".data.data.KAFKA_BROKER" secret.json)

          echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> $GITHUB_ENV
          echo "MONGO_URI=$MONGO_URI" >> $GITHUB_ENV
          echo "KAFKA_BROKER=$KAFKA_BROKER" >> $GITHUB_ENV

      - name: 🐳 Docker Build
        run: |
          docker build \
            --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
            --build-arg MONGO_URI=$MONGO_URI \
            --build-arg KAFKA_BROKER=$KAFKA_BROKER \
            -t profinaut:dev .